### ISSUE TITLE
Failed to download launcher and permission errors on release 20201210

### ISSUE THREAD

**Issue by someonewithpc** [CreeperHost/modpacklauncher#21]
I installed this app on Arch Linux with the PKGBUILD from https://aur.archlinux.org/packages/ftba/#comment-779578 with the version updated to `202012101153-ce008c54b4-release`. The app runs, but the modpacks don't (specifically FTB Interactions). I noticed that `/opt/FTBA` is owned by `root`, but changing the owner to my user and group made it so there was no output (and it still didn't work). Running with `sudo` exits with code `0` without doing anything.

The first time I ran it I got an error saying it failed to download the minecraft launcher.

Here's the output of running FTBApp as installed

```
$ FTBApp 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Dec 10, 2020 6:43:36 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Loaded 0 out of 0 instances.
Dec 10, 2020 6:43:36 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Loaded 0 out of 0 instances.
Dec 10, 2020 6:43:36 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: No PID args
java.nio.file.FileSystemException: /opt/FTBA/bin/ftb-app: Operation not permitted
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:254)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:276)
	at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2079)
	at net.creeperhost.creeperlauncher.util.FileUtils.setFilePermissions(FileUtils.java:227)
	at net.creeperhost.creeperlauncher.CreeperLauncher.startElectron(CreeperLauncher.java:534)
	at net.creeperhost.creeperlauncher.CreeperLauncher.main(CreeperLauncher.java:345)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
	at install4j.net.creeperhost.creeperlauncher.CreeperLauncher.main(Unknown Source)
Dec 10, 2020 6:43:36 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Server started successfully - 202012101153-ce008c54b4-release
Dec 10, 2020 6:43:36 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Starting Electron: /opt/FTBA/bin/ftb-app --ws 16731:29e39635-e002-4542-a039-62989802f654 --pid 629521
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: 18:43:37.139 › We have a --ws
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
18:43:37.143 › electron-log.transports.file: Can't write to /opt/FTBA/bin/electron.log Error: EACCES: permission denied, open '/opt/FTBA/bin/electron.log'
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: 18:43:37.145 › Got the lock
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at Object.openSync (fs.js:440:3)
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at Object.writeFileSync (fs.js:1265:35)
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at h.testFileWriting (/opt/FTBA/bin/resources/app.asar/background.js:1:191555)
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at h.createFile (/opt/FTBA/bin/resources/app.asar/background.js:1:191088)
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at h.provide (/opt/FTBA/bin/resources/app.asar/background.js:1:190915)
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at d (/opt/FTBA/bin/resources/app.asar/background.js:1:188385)
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at l (/opt/FTBA/bin/resources/app.asar/background.js:1:187884)
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at i (/opt/FTBA/bin/resources/app.asar/background.js:1:21434)
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at n (/opt/FTBA/bin/resources/app.asar/background.js:1:21226)
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
18:43:37.240 › (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
18:43:37.252 › (node:629745) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
Dec 10, 2020 6:43:37 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Front end connected: /127.0.0.1:47736
Dec 10, 2020 6:43:46 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: closed null with exit code 1001 additional info: 
```

`~/.ftba/ftbapp.log`
```
Dec 10, 2020 7:02:01 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Loaded 1 out of 1 instances.
Dec 10, 2020 7:02:01 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Loaded 1 out of 1 instances.
Dec 10, 2020 7:02:01 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: No PID args
Dec 10, 2020 7:02:01 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Starting Electron: /opt/FTBA/bin/ftb-app --ws 16977:bc6ef96e-b13c-472f-833f-5456a88893af --pid 637944
Dec 10, 2020 7:02:01 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Server started successfully - 202012101153-ce008c54b4-release
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: 19:02:02.077 › We have a --ws
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
19:02:02.081 › electron-log.transports.file: Can't write to /opt/FTBA/bin/electron.log Error: EACCES: permission denied, open '/opt/FTBA/bin/electron.log'
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: 19:02:02.083 › Got the lock
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at Object.openSync (fs.js:440:3)
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at Object.writeFileSync (fs.js:1265:35)
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at h.testFileWriting (/opt/FTBA/bin/resources/app.asar/background.js:1:191555)
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at h.createFile (/opt/FTBA/bin/resources/app.asar/background.js:1:191088)
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at h.provide (/opt/FTBA/bin/resources/app.asar/background.js:1:190915)
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at d (/opt/FTBA/bin/resources/app.asar/background.js:1:188385)
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at l (/opt/FTBA/bin/resources/app.asar/background.js:1:187884)
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at i (/opt/FTBA/bin/resources/app.asar/background.js:1:21434)
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
    at n (/opt/FTBA/bin/resources/app.asar/background.js:1:21226)
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
19:02:02.177 › (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19)
19:02:02.199 › (node:638026) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
Dec 10, 2020 7:02:02 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Front end connected: /127.0.0.1:39068
Dec 10, 2020 7:02:05 PM net.creeperhost.creeperlauncher.CreeperLogger warning
WARNING: Starting launcher at /home/hugo/.ftba/bin
Dec 10, 2020 7:02:05 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.minecraft.GameLauncher.launchGame(GameLauncher.java:89)
en_US
Dec 10, 2020 7:02:05 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.minecraft.GameLauncher.launchGame(GameLauncher.java:117)
Unable to launch vanilla launcher! 
class java.io.IOException: Cannot run program "/home/hugo/.ftba/bin/minecraft-launcher/minecraft-launcher": error=2, No such file or directory
java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
net.creeperhost.creeperlauncher.minecraft.GameLauncher.launchGame(GameLauncher.java:90)
net.creeperhost.creeperlauncher.pack.LocalInstance.lambda$play$10(LocalInstance.java:534)
java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

Dec 10, 2020 7:02:05 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.pack.LocalInstance.play(LocalInstance.java:571)
Unable to initialize MineTogether Connect!
Dec 10, 2020 7:02:07 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: closed null with exit code 1001 additional info: 
```

**Comment by voidstarr** [comment]
I am having similar issues with the FTBA_unix_202012101153-ce008c54b4-release.sh script from feed-the-beast.com on Ubuntu Mate 20.04. On first launch, the minecraft launcher is not unpacked properly in ~/.ftba/bin. Resolving that issue leaves me with with the "Unable to initialize MineTogether Connect!" error above.

**Comment by ThePaul-T** [comment]
The MineTogether Connect message is expected and does not impact game launching. The launcher is missing in the log above.

**Comment by someonewithpc** [comment]
@ThePaul-T No, I know it is missing, but I don't know where to get it from, couldn't find it in any folder, and clearly it didn't work automatically

**Comment by ThePaul-T** [comment]
It will have downloaded it but failed to extract it, it will be inside ~/.ftba/bin, there will be a tar.gz, just extract it there and it should work.

**Comment by gigabit101** [comment]
I believe this issue should be resolved with the changes that have been made with how we handle downloading the vanilla launcher 
If the issue continues please do let us know.
