### ISSUE TITLE
Java errors preventing start of FTB App.

### ISSUE THREAD

**Issue by Dewidos** [CreeperHost/modpacklauncher#27]
My FTB App is stuck on loading screen, I got this in logs:

[10:07:50] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Reloading instances..
[10:07:50] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Skipping Cloud instance reload.
[10:07:50] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Instances directory missing, skipping..
[10:07:50] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Finished instance reload in 6ms(6195800ns)
[10:07:50] [main/INFO] [net.creeperhost.creeperlauncher.CreeperLauncher]: Overwolf integration mode
[10:07:50] [WebSocketSelector-40/INFO] [net.creeperhost.creeperlauncher.api.WebSocketAPI]: Server started successfully - 202106032039-901edde0d3-prototyping
[10:07:50] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Reloading instances..
[10:07:50] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Skipping Cloud instance reload.
[10:07:50] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Loaded 0 out of 0 instances in 4017200ns.
[10:07:50] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Finished instance reload in 6ms(6578200ns)
[10:07:50] [WebSocketWorker-24/INFO] [net.creeperhost.creeperlauncher.api.WebSocketAPI]: Front end connected: /127.0.0.1:52204 - sending our socket and secret and relaunching websocket
[10:07:50] [WebSocketSelector-40/INFO] [net.creeperhost.creeperlauncher.api.WebSocketAPI]: closed null with exit code 1000 additional info: 
[10:07:50] [WebSocketSelector-59/INFO] [net.creeperhost.creeperlauncher.api.WebSocketAPI]: Server started successfully - 202106032039-901edde0d3-prototyping
[10:07:50] [WebSocketWorker-43/INFO] [net.creeperhost.creeperlauncher.api.WebSocketAPI]: Front end connected: /127.0.0.1:52210
[10:07:50] [ForkJoinPool-1-worker-19/ERROR] [net.creeperhost.creeperlauncher.api.WebSocketMessengerHandler]: Error handling message
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Unmapped relationship: 7
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: Unmapped relationship: 7
	at com.sun.jna.platform.win32.WinNT$SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX.fromPointer(WinNT.java:2999) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformationEx(Kernel32Util.java:715) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at oshi.driver.windows.LogicalProcessorInformation.getLogicalProcessorInformationEx(LogicalProcessorInformation.java:61) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at oshi.hardware.platform.windows.WindowsCentralProcessor.initProcessorCounts(WindowsCentralProcessor.java:155) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:74) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:66) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createProcessor(WindowsHardwareAbstractionLayer.java:61) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at net.creeperhost.creeperlauncher.api.data.other.SettingsInfoData$Reply.<init>(SettingsInfoData.java:21) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.other.SettingsInfoHandler.handle(SettingsInfoHandler.java:15) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.other.SettingsInfoHandler.handle(SettingsInfoHandler.java:9) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.IMessageHandler.handle(IMessageHandler.java:10) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at net.creeperhost.creeperlauncher.api.WebSocketMessengerHandler.lambda$handleMessage$0(WebSocketMessengerHandler.java:134) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	... 7 more
[10:07:51] [ForkJoinPool-1-worker-19/ERROR] [net.creeperhost.creeperlauncher.api.WebSocketMessengerHandler]: Error handling message
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Unmapped relationship: 7
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: Unmapped relationship: 7
	at com.sun.jna.platform.win32.WinNT$SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX.fromPointer(WinNT.java:2999) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformationEx(Kernel32Util.java:715) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at oshi.driver.windows.LogicalProcessorInformation.getLogicalProcessorInformationEx(LogicalProcessorInformation.java:61) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at oshi.hardware.platform.windows.WindowsCentralProcessor.initProcessorCounts(WindowsCentralProcessor.java:155) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:74) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:66) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createProcessor(WindowsHardwareAbstractionLayer.java:61) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at net.creeperhost.creeperlauncher.api.data.other.SettingsInfoData$Reply.<init>(SettingsInfoData.java:21) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.other.SettingsInfoHandler.handle(SettingsInfoHandler.java:15) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.other.SettingsInfoHandler.handle(SettingsInfoHandler.java:9) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.IMessageHandler.handle(IMessageHandler.java:10) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	at net.creeperhost.creeperlauncher.api.WebSocketMessengerHandler.lambda$handleMessage$0(WebSocketMessengerHandler.java:134) ~[launcher-202106032039-901edde0d3-prototyping-all.jar:?]
	... 7 more

I tried reinstalling minecraft, whole overwolf and java, nothing helped. It can be an issue with Windows 11, but I am not sure. I am asking for ASAP help and fix.

**Comment by gigabit101** [comment]
Is this issue still present when using the latest version of the app?
